#### checked this with Ulrike : ####
# Cleveland Daten um WK erweitern:
# 1) start with original Cleveland data set, 10 features / predictors, 1 target (CAD)
# 2) add column "prob" to the Cleveland table, probabilities generated by a logistic regression model (or any other model, like RF...) based on the original Cleveland data set. This is now the enriched Cleveland data set.

# later draw a bootstrap sample (or many...) from the enriched Cleveland data set
# and recreate / the CAD column : 
# CAD values are 0/1 drawn under a binomial distribution with parameter of success p=prob

#load('data/data_SupMat4.rda') # removed 22.3.22

print('Sourcing sim-prep-v2.R : contains functions create_prob() and new_bootstrap() ')

create_prob <- function(df){
  #' create a probability column based on a target colum
  #' 
  #' @param df a data frame with a CAD column
  #' build a logistic model on df. 
  #' Its fitted values are the new probabilities.
  
  if('CAD_fac' %in% names(df)){
    df$CAD_fac <-  NULL
  }
  
  if('CAD' %in% names(df)){
    # nothing
    }else{
    simpleError('data needs a CAD column as target')
  }

  model <- glm(CAD ~.,family=binomial(link='logit'), data=df)
  df$prob <- model$fitted.values
  return(df)
}


new_bootstrap <- function(df, resample){
  dfb<-df[resample,] # we need the prob to replace CAD 
  dfb$CAD <- factor(rbinom(303,1,dfb$prob))
  levels(dfb$CAD)<-list("No"="0","Yes"="1")
  return(dfb)
}
